### ISSUE TITLE
Docker example not working in 19.03

### ISSUE THREAD

**Issue by jan-thoma** [crowdrender/cr-docker#1]
With Docker 19.03 the provided examples are not working, because token is not prepended with `--env`. For use with GPU and port forwarding it would be better to provide a more complete example

`docker run -t -d -p 9000-9025:9000-9025 --restart always --gpus all --name "crowdrender-Server" --env token=<token> zocker160/blender-crowdrender:nvidia`

**Comment by Jeducious** [comment]
Hi Jan, does your example work for both nvidia and OpenCL GPUs?

**Comment by jan-thoma** [comment]
It's working for our nvidia GPU's we don't have any OpenCL capable GPU's here to to test

**Comment by zocker-160** [comment]
@jan-thoma thank you for reporting the issue! 
That was fully my mistake, don't know what I was thinking....
