### ISSUE TITLE
ModuleNotFoundError: No module named 'zmq'

### ISSUE THREAD

**Issue by Charmandrigo** [crowdrender/cr-docker#18]
I am trying to install crowdrender for the first time, prepared a new machine with a fresh install of Linux Lite (Ubuntu 22 based)
installed everything required for GPU, and I keep getting a error

> Digest: sha256:6f744e4202d06c16a669977adb498b1a4d98a774c67951beca4ed09a0abe5e5c
> 
> Status: Downloaded newer image for crowdrender/blender-crowdrender:latest
> 
> machine_uuid is not set...generating new unique UUID.....
> 
> downloading version latest of crowdrender......
> 
> download token given with length of 137
> 
> downloading latest CR version!
> 
> ############################################################################################################################################################### 100.0%
> 
> installing crowdrender addon.......
> 
> Blender 3.2.1 (hash a2d59b2dac9e built 2022-07-05 23:53:28)
> 
> addon_utils.disable: crowdrender not disabled
> 
> Modules Installed (crowdrender) from '/CR/latest.zip' into '/root/.config/blender/3.2/scripts/addons'
> 
> Info: Modules Installed (crowdrender) from '/CR/latest.zip' into '/root/.config/blender/3.2/scripts/addons'
> 
> Info: Modules Installed (crowdrender) from '/CR/latest.zip' into '/root/.config/blender/3.2/scripts/addons'
> 
> Exception in module register(): /root/.config/blender/3.2/scripts/addons/crowdrender/__init__.py
> 
> Traceback (most recent call last):
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 91, in <module>
> 
>     import zmq
> 
> ModuleNotFoundError: No module named 'zmq'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/blender/3.2/scripts/modules/addon_utils.py", line 371, in enable
> 
>     mod.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/__init__.py", line 141, in register
> 
>     cr_source.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 78, in register
> 
>     select_versions()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 67, in select_versions
> 
>     from . import bl_addon
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 115, in <module>
> 
>     raise ImportError(
> 
> ImportError: CrowdRender is not able to run because it can't import necessarycomponents, please e-mail us at [info@crowdrender.com.au](mailto:info@crowdrender.com.au) to report this.
> 
> 
> Error: Traceback (most recent call last):
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 91, in <module>
> 
>     import zmq
> 
> ModuleNotFoundError: No module named 'zmq'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/blender/3.2/scripts/modules/addon_utils.py", line 371, in enable
> 
>     mod.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/__init__.py", line 141, in register
> 
>     cr_source.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 78, in register
> 
>     select_versions()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 67, in select_versions
> 
>     from . import bl_addon
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 115, in <module>
> 
>     raise ImportError(
> 
> ImportError: CrowdRender is not able to run because it can't import necessarycomponents, please e-mail us at [info@crowdrender.com.au](mailto:info@crowdrender.com.au) to report this.
> 
> 
> Error: Traceback (most recent call last):
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 91, in <module>
> 
>     import zmq
> 
> ModuleNotFoundError: No module named 'zmq'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/blender/3.2/scripts/modules/addon_utils.py", line 371, in enable
> 
>     mod.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/__init__.py", line 141, in register
> 
>     cr_source.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 78, in register
> 
>     select_versions()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 67, in select_versions
> 
>     from . import bl_addon
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 115, in <module>
> 
>     raise ImportError(
> 
> ImportError: CrowdRender is not able to run becaError: Python: Traceback (most recent call last):
> 
>   File "/CR/./install_addon.py", line 7, in <module>
> 
>     bpy.ops.preferences.addon_enable(module='crowdrender')
> 
>   File "/usr/local/blender/3.2/scripts/modules/bpy/ops.py", line 115, in __call__
> 
>     ret = _op_call(self.idname_py(), None, kw)
> 
> RuntimeError: Error: Traceback (most recent call last):
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 91, in <module>
> 
>     import zmq
> 
> ModuleNotFoundError: No module named 'zmq'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/blender/3.2/scripts/modules/addon_utils.py", line 371, in enable
> 
>     mod.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/__init__.py", line 141, in register
> 
>     cr_source.register()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 78, in register
> 
>     select_versions()
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/__init__.py", line 67, in select_versions
> 
>     from . import bl_addon
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/bl_addon/__init__.py", line 115, in <module>
> 
>     raise ImportError(
> 
> ImportError: CrowdRender is not able to run because it can't import necessarycomponents, please e-mail us at [info@crowdrender.com.au](mailto:info@crowdrender.com.au) to report this.
> 
> ... truncated
> 
> Blender quit
> 
> Blender launch test:
> 
> Blender 3.2.1 (hash a2d59b2dac9e built 2022-07-05 23:53:28)
> 
> Blender 3.2.1
> 
> 	build date: 2022-07-05
> 
> 	build time: 23:53:28
> 
> 	build commit date: 2022-07-05
> 
> 	build commit time: 15:44
> 
> 	build hash: a2d59b2dac9e
> 
> 	build platform: Linux
> 
> 	build type: release
> 
> 	build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -D_GLIBCXX_USE_CXX11_ABI=0  
> 
> 	build c++ flags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -D_GLIBCXX_USE_CXX11_ABI=0  
> 
> 	build link flags:  -Wl,--version-script='/home/blender/git/blender-v320/blender.git/source/creator/blender.map'
> 
> 	build system: CMake
> 
> replacing CR_PATH for CR >= 0.4.0...
> 
> starting crowdrender server in CLOUD MODE.....................
> 
> Blender 3.2.1 (hash a2d59b2dac9e built 2022-07-05 23:53:28)
> 
> Error: Python: Traceback (most recent call last):
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/core/serv_int_start.py", line 84, in <module>
> 
>     from cr_source.core import server_interface
> 
>   File "/root/.config/blender/3.2/scripts/addons/crowdrender/cr_source/core/server_interface.py", line 32, in <module>
> 
>     import zmq
> 
> ModuleNotFoundError: No module named 'zmq'

python3 is already bundled in ubuntu, so I don't know what is missing here, I am using the command given by this github page and my login token, this is a fresh new install of Linux

**Comment by zocker-160** [comment]
what version of docker do you have installed?

**Comment by Charmandrigo** [comment]
> what version of docker do you have installed?

Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Comment by zocker-160** [comment]
do you use a free account?

If yes, then Blender 2.93 is the highest version you can use, as specified in the readme: https://github.com/crowdrender/cr-docker#cr_version-table

This error to me looks like you are trying to run CR v0.4.1 with Blender 3.2.1 which will not work.

**Comment by Charmandrigo** [comment]
Alright that seems to have been the problem, tried again with the suscription and it worked

**Comment by zocker-160** [comment]
thank you for supporting our work!

**Comment by Jeducious** [comment]
Yes, thank you @Charmandrigo!! Glad to hear it is working now :)
