### ISSUE TITLE
How do I use a specific blender version for latest?

### ISSUE THREAD

**Issue by Charmandrigo** [crowdrender/cr-docker#19]
downloading the latest version of cr-Docker seems to auto download blender 3.2, the issue is I am using Blender 3.1 stable currently and don't want to update right now because several of my addons stopped working on the most recent build. Documentation mentions both master and clients need to be on the same version on blender, the page says the latest crowdrender works on 2.8 - 3.2, so how do I make the client computers run on the same blender 3.1? I keep getting "sync failed" and crashes instantly when I hit render image probably because of this

**Comment by zocker-160** [comment]
Please use the `bl_3.1` tag if you want to use Blender 3.1.

It was not specified in the readme, because 3.1 is EOL.
