### ISSUE TITLE
Use download latest addon file endpoint

### ISSUE THREAD

**Issue by Smilebags** [crowdrender/cr-docker#5]
This issue is here as a reminder to create and use a new endpoint which will download the latest available addon version for the current user. This simplifies the docker image and should reduce maintenance costs here. This will be updated once the server supports this feature.

**Comment by zocker-160** [comment]
:+1:  this would be great.

Additionally it would be nice having the option to fetch all available version, maybe including the info which ones are free.

With this information I could automatically update the image and maybe even the readme without the need to manually edit it.

**Comment by zocker-160** [comment]
implemented with 3e600250bed254972237cdf6144f23a4b79d682b and  575283036282666c9f3ab49ce2ac72ccd727da00.
