### ISSUE TITLE
should be documented that beta version fails with error unless you pay

### ISSUE THREAD

**Issue by psiho** [crowdrender/cr-docker#6]
Just lost an hour debugging and installing this Docker only to find out that reason is that latest beta is not available to me. I guess downloader fails to download beta and instead of notifying about the reasons (which would still be too late to inform us about it), it just fails with a weird error. 

If I'm correct that this is the reason for the error, it would be only fair to state this requirement on this page and on Dockerhub page instructions next to "beta" version description. I'm sure it would save time and frustration to many people trying this out.

**Comment by zocker-160** [comment]
We have documented in the readme in the version table, that if you use the `beta` tag, it will be using CR version 0.2.9.
As of right now this version is only available for supporters.

Also as documented, you can specify the CR version yourself (works with `beta` too).

So in order to use the latest public available CR you just add `-e CR_VERSION=cr_025_bl280`.

**Comment by psiho** [comment]
> We have documented in the readme in the version table, that if you use the `beta` tag, it will be using CR version 0.2.9.

That was clear. So people having 2.9 go for beta.

> As of right now this version is only available for supporters.

That is NOT clear from this page and readme on Github/Dockerhub. And I'm pretty sure not many people using Docker installs will go over your website to check for this. At least not before Docker image is working. And it is not, fails with error "no such file or directory". So that's the whole point. An hour lost. I don't see a need to hide here the fact that certain versions are not free.

> Also as documented, you can specify the CR version yourself (works with beta too).
> So in order to use the latest public available CR you just add -e CR_VERSION=cr_025_bl280.

That is also clear, but not related to the question. However I specify beta version, it fails until I pay.

**Comment by zocker-160** [comment]
> That is NOT clear from this page and readme on Github/Dockerhub. And I'm pretty sure not many people using Docker installs will go over your website to check for this. At least not before Docker image is working. And it is not, fails with error "no such file or directory". So that's the whole point. An hour lost. I don't see a need to hide here the fact that certain versions are not free.

Ah yeah I now understand where you are coming from and yes I fully agree with you, the documentation lacks that information,
I am sorry for that, it will be fixed asap.

And also yes the logging is not great, I am planning on improving that, by giving more meaningful error messages.

**Comment by Jeducious** [comment]
Yeah, my apologies too, we missed this as a potentially misleading problem, sorry about that @psiho :S
